cc_library(name = 'search_term',
           srcs = [
                   'searchTerm.cpp',
                   'tl_codetbl.cpp',
                   'fileOperation.cpp',
                   'simpleDic.cpp',
                   'Utility.cpp'],
           deps = [
                  ],
           warning = 'no',
          )

